print("Learning git makes me happy.")
print("But git is so complex.")
name = input("What is your name? ")
print("If you can hear me,run!")
response = input("Who is that in the vecna's body? 11 or Will?")